### ISSUE TITLE
Benefits

### ISSUE THREAD

**Issue by murphy** [crypto-credit-association/cca-website#11]
We need a new section / area for membership benefits. Please design and implement something.

Here are the benefits:

**Individual**
* Access to members-only content.
* 50% discount on Individual CLIC (http://www.usteta.org/crypto-logic-integrity-committee/) membership.

**Corporate**
* Access to members-only content.
* 50% discount on Corporate CLIC (http://www.usteta.org/crypto-logic-integrity-committee/) membership.

**Enterprise**
* Access to members-only content.
* 50% discount on Silver, Gold, or Platinum CLIC (http://www.usteta.org/crypto-logic-integrity-committee/) membership.

**Charter**
* Access to members-only content.
* No membership fees due for 10 years.
* 10% discount on Corporate or Enterprise membership fees after 10 years.
* 50% discount on Corporate, Silver, Gold, or Platinum CLIC (http://www.usteta.org/crypto-logic-integrity-committee/) membership.

**Comment by elektramurphy** [comment]
@murphy How's this? https://staging--cca-staging.netlify.app/membership-benefits

I'll implement any feedback and we can push it live
