### ISSUE TITLE
LinkedIn page/article sharing needs some work

### ISSUE THREAD

**Issue by dogecoinistheworldsbestcryptocurrency** [crypto-credit-association/cca-website#13]
- Credmark is somehow still in there
- I have no idea where LinkedIn pulls a logo - it doesn't currently

Any ideas on making our content a bit more LinkedIn friendly?  This is what a fresh post will look like by default:

![Capture](https://user-images.githubusercontent.com/127889953/225722598-6a6ee491-f217-42cf-a59c-da0a6c190db8.PNG)

This is what it looks like when posted:

https://www.linkedin.com/posts/crypto-credit-association_a-call-to-action-risk-management-through-activity-7042204015870242816-D2I-?utm_source=share&utm_medium=member_desktop

**Comment by elektramurphy** [comment]
@dogecoinistheworldsbestcryptocurrency I'll fix the title issue but in order to add an image to appear we'd need to add one to the CMS. Do we have a plan for this since there's no designer? Do you want to use generic stock images? 

If yes, I'll add in an image field and we can populate that to pull through.

**Comment by elektramurphy** [comment]
@dogecoinistheworldsbestcryptocurrency I think we should also add a description box to add to the sharing link

**Comment by dogecoinistheworldsbestcryptocurrency** [comment]
Hey, how much text do you need / what dimensions should the image be?  I can throw something together easily.

**Comment by dogecoinistheworldsbestcryptocurrency** [comment]
Hi just coming back to this - can I provide something?

**Comment by elektramurphy** [comment]
@dogecoinistheworldsbestcryptocurrency Nope, ticket was completed! Apologies forgot to close it, will do that now.
